version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/material"
    versions:
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/router"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular-devkit/core"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/pwa"
    versions:
    - 0.1101.1
    - 0.1101.2
    - 0.1101.4
    - 0.1102.0
    - 0.1102.1
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.8
    - 0.1102.9
  - dependency-name: "@angular/platform-browser-dynamic"
    versions:
    - 11.2.10
    - 11.2.9
  - dependency-name: "@angular/compiler"
    versions:
    - 11.2.10
    - 11.2.9
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.9
  - dependency-name: "@angular/common"
    versions:
    - 11.2.10
    - 11.2.9
  - dependency-name: "@angular/forms"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
  - dependency-name: "@angular-devkit/schematics"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
  - dependency-name: "@angular/service-worker"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
  - dependency-name: "@angular-devkit/architect"
    versions:
    - 0.1101.1
    - 0.1101.2
    - 0.1101.4
    - 0.1102.0
    - 0.1102.1
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
  - dependency-name: ts-node
    versions:
    - 9.1.1
